[package]
name = "ws-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
futures-util = "0.3.29"
tokio = { version = "1.33.0", features = ["full"] }
tokio-stream = "0.1.14"
warp = "0.3.6"
